name: Push To Branch

run-name: ${{github.actor}} Pushed To ${{github.ref_name}}

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install npm version 10
        run: npm i -g npm@10

      - name: Install Dependencies
        run: npm ci

  audit:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: npm run audit --audit-level=moderate

  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: npm run test
